### ISSUE TITLE
Crash with large enums

### ISSUE THREAD

**Issue by Omnicrash** [xaviersolau/GeneratorTools#67]
I'm currently using the localization generator, and it seems to crash the generator tools when a very large enum exists in the project.

I've attached the enum that causes the issue (renamed to log so GitHub allows it).

The error message:
`Unhandled exception: System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at SoloX.GeneratorTools.Core.CSharp.Generator.Selectors.AttributeSelector`1.<>c.<GetDeclarations>b__0_1(IDeclaration`1 d)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at SoloX.GeneratorTools.Core.CSharp.Generator.Impl.AutomatedGenerator.Generate(IEnumerable`1 files)
   at Tools.LocalizationGen.Implementations.LocalizationGenerator.Generate(ICSharpWorkspace workspace, ILocator locator, IWriter fileWriter, ILocator jsonLocator, IReader jsonReader, IWriter jsonWriter, IEnumerable`1 files, GeneratorOptions generatorOptions) `

[Country.cs.log](https://github.com/user-attachments/files/17428127/Country.cs.log)

**Comment by xaviersolau** [comment]
Thanks for the bug report, I'm going to have a look.

**Comment by xaviersolau** [comment]
What version of the tool do you use?
Is it the simple fact the enum is in you project or do you use the enum?

**Comment by Omnicrash** [comment]
Update: It seemed that it has issues with any enum being added to this project; resolved by updating generators to alpha.43.
